spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driverhttps://github.com/codestates-seb/seb40_pre_013/security
    url: jdbc:mysql://pre-project-database.c7tzer7zrsxo.ap-northeast-2.rds.amazonaws.com:3306/pre_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: {RDS Mysql id}
    password: {RDS Mysql password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
