
spring:
#  h2:
#    console:
#      enabled: true
#    path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # SQL 출력
    properties:
      hibernate:
        format_sql: true # SQL pretty print
  sql:
    init:
      data-locations:
        classpath*: db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG  # jpa DEBUG
server:
  servlet:
    encoding:
      force-response: true  # UTF-8