
spring:
#  h2:
#    console:
#      enabled:
#      truepath: /h2
#  datasource:
#    url: jdbc:h2:mem:test
  redis:
    lettuce:
      pool:
        max-active: 5 #pool에 할당될 수 잇는 커넥션 최대수(음수로 하면 무제한)
        max-idle: 5 #pool의 idle 커넥션 최대수(음수는 무제한)
        max-wait: 2 #풀에서 관리하는 idle 커넥션의 최소 수 대상

    host: 127.0.0.1
    port: 6379
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true # SQL 출력
    properties:
      hibernate:
        format_sql: true # SQL pretty print
  sql:
    init:
      data-locations:
        classpath*: db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG  # jpa DEBUG
server:
  servlet:
    encoding:
      force-response: true  # UTF-8
jwt:
  secret-key : ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
